### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'contrib'

### ISSUE THREAD

**Issue by Liquid72** [Khaivdo/How-to-train-an-Object-Detector-using-Tensorflow-API-on-Ubuntu-16.04-GPU#1]
(venv) rico@rfppc12222:~/Desktop/models/research$ python object_detection/builders/model_builder_test.py
Traceback (most recent call last):
  File "object_detection/builders/model_builder_test.py", line 23, in <module>
    from object_detection.builders import model_builder
  File "/home/rico/Desktop/models/research/object_detection/builders/model_builder.py", line 22, in <module>
    from object_detection.builders import box_predictor_builder
  File "/home/rico/Desktop/models/research/object_detection/builders/box_predictor_builder.py", line 20, in <module>
    from object_detection.predictors import convolutional_box_predictor
  File "/home/rico/Desktop/models/research/object_detection/predictors/convolutional_box_predictor.py", line 23, in <module>
    slim = tf.contrib.slim
AttributeError: module 'tensorflow' has no attribute 'contrib'

**Comment by Khaivdo** [comment]
Hi Ricftrw,
Which version of Tensorflow are you using? The `tf.contrib` has been removed in TF 2.0 which might be the reason of your problem as explained [here](https://stackoverflow.com/questions/55870127/module-tensorflow-has-no-attribute-contrib)

**Comment by Daegas** [comment]
Download the commit of tensorflow/models for your tensorflow installed version. 

TensorFlow version | GitHub Models Repository Commit
-- | --
TF v1.7 | https://github.com/tensorflow/models/tree/adfd5a3aca41638aa9fb297c5095f33d64446d8f
TF v1.8 | https://github.com/tensorflow/models/tree/abd504235f3c2eed891571d62f0a424e54a2dabc
TF v1.9 | https://github.com/tensorflow/models/tree/d530ac540b0103caa194b4824af353f1b073553b
TF v1.10 | https://github.com/tensorflow/models/tree/b07b494e3514553633b132178b4c448f994d59df
TF v1.11 | https://github.com/tensorflow/models/tree/23b5b4227dfa1b23d7c21f0dfaf0951b16671f43
TF v1.12 | https://github.com/tensorflow/models/tree/r1.12.0
TF v1.13 | https://github.com/tensorflow/models/tree/r1.13.0
Latest version | https://github.com/tensorflow/models

As shown in this repository: https://github.com/EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10#1-install-anaconda-cuda-and-cudnn
